#! /bin/sh -> josuerom
pgrep -x sxhkd > /dev/null || sxhkd &

# cambio de resolución de pantalla
xrandr -s 1920x1080 -r 60.00
# visualización de barra superior
$HOME/.config/polybar/launch.sh
# efecto de transparencia
picom &
# fondo de pantalla
feh --bg-fill ~/Imágenes/Walls/01.png &
# distribución del teclado en latinoamericano
setxkbmap latam &
# cambio de barra superior personalizada
#xrdb merge $HOME/xresources/catppuccin &

# dispongo de solo 4 escritorios
bspc monitor $(xrandr | grep -w connected | awk -F'[ \+]' '{print $1}') -d 1 2 3 4 &

bspc config border_width         0.2
bspc config window_gap           9
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a * state=tiled
